### ISSUE TITLE
Unstyled search bar and artist description

### ISSUE THREAD

**Issue by joshsleeper** [macfeaster/play-music-black#14]
Looks like some recent CSS changes have broken styling on at least the search bar and the artist description popup.

## unstyled search bar example

![image](https://user-images.githubusercontent.com/849941/70363480-8bcddd00-1856-11ea-970b-37a6925a31c1.png)

## unstyled artist description popup example

![image](https://user-images.githubusercontent.com/849941/70363487-94beae80-1856-11ea-8d7f-2f037d1d2bdf.png)

**Comment by macfeaster** [comment]
Like the other recent changes, these must be partial rollout because I'm yet again unable to reproduce. 😛 Guessing like with the other changes that some existing selectors can be modified slightly to include the new cases.

**Comment by StewMcc** [comment]
How do you get the artist popup thing? Not sure if just being blind but can't find it haha.

**Comment by joshsleeper** [comment]
Given that Trapt is who I used in my example, I'll link to them so the equivalent text is more obvious~

https://play.google.com/music/listen?u=0#/artist/Aqkymdc634mfzeaphoah5culnne/Trapt

Under the artist name at the top of their artist page, you can see some descriptive text that is generally cut off because it's relatively long. That text is actually clickable!

![image](https://user-images.githubusercontent.com/849941/71257963-0856c600-2303-11ea-8990-1e726f2d094d.png)

**Comment by StewMcc** [comment]
Paper dialog changes in #17 appear to fix this as well. Thanks for pointing that out, forgot that was a thing haha
